# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/tewesday/Desktop/UnrealEngine
GAMEPROJECTFILE =/home/tewesday/Documents/UnrealProjects/RealmDemo/RealmDemo.uproject

TARGETS = \
	UnrealClient-Linux-Debug  \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Test  \
	UnrealClient-Linux-Shipping  \
	UnrealClient \
	UnrealEditor-Linux-Debug  \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Test  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-Debug  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Test  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UnrealServer-Linux-Debug  \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Test  \
	UnrealServer-Linux-Shipping  \
	UnrealServer \
	RealmDemo-Linux-Debug  \
	RealmDemo-Linux-DebugGame  \
	RealmDemo-Linux-Test  \
	RealmDemo-Linux-Shipping  \
	RealmDemo \
	RealmDemoEditor-Linux-Debug  \
	RealmDemoEditor-Linux-DebugGame  \
	RealmDemoEditor-Linux-Test  \
	RealmDemoEditor-Linux-Shipping  \
	RealmDemoEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend RealmDemoEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug RealmDemoEditor-Linux-Debug


UnrealClient-Linux-Debug:
	 $(BUILD) UnrealClient Linux Debug  $(ARGS)

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  $(ARGS)

UnrealClient-Linux-Test:
	 $(BUILD) UnrealClient Linux Test  $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  $(ARGS)

UnrealClient:
	 $(BUILD) UnrealClient Linux Development  $(ARGS)

UnrealEditor-Linux-Debug:
	 $(BUILD) UnrealEditor Linux Debug  $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Test:
	 $(BUILD) UnrealEditor Linux Test  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-Debug:
	 $(BUILD) UnrealGame Linux Debug  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Test:
	 $(BUILD) UnrealGame Linux Test  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealServer-Linux-Debug:
	 $(BUILD) UnrealServer Linux Debug  $(ARGS)

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  $(ARGS)

UnrealServer-Linux-Test:
	 $(BUILD) UnrealServer Linux Test  $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  $(ARGS)

UnrealServer:
	 $(BUILD) UnrealServer Linux Development  $(ARGS)

RealmDemo-Linux-Debug:
	 $(PROJECTBUILD) RealmDemo Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

RealmDemo-Linux-DebugGame:
	 $(PROJECTBUILD) RealmDemo Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RealmDemo-Linux-Test:
	 $(PROJECTBUILD) RealmDemo Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

RealmDemo-Linux-Shipping:
	 $(PROJECTBUILD) RealmDemo Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RealmDemo:
	 $(PROJECTBUILD) RealmDemo Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

RealmDemoEditor-Linux-Debug:
	 $(PROJECTBUILD) RealmDemoEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

RealmDemoEditor-Linux-DebugGame:
	 $(PROJECTBUILD) RealmDemoEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RealmDemoEditor-Linux-Test:
	 $(PROJECTBUILD) RealmDemoEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

RealmDemoEditor-Linux-Shipping:
	 $(PROJECTBUILD) RealmDemoEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RealmDemoEditor:
	 $(PROJECTBUILD) RealmDemoEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
